### ISSUE TITLE
рівні заголовків і семантика

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Blur-Landing-Site#1]
https://github.com/VasylUlianovskyi/Blur-Landing-Site/blob/8679e3929a038dcea6c90526ccc3fbed99e8edfa/index.html#L31
- пропущено заголовок другого рівня. Точніше, мабуть, він не має бути видимий користувачу. Я про це казала на початку заняття в сб, 13.04. Тут можна використати якраз такий прийом. Ну і я б помістила кожен іконку/заголовок/текст в section, оскільки це як струкрутна одиниця зі своїм заголовком.
- заголовок About Us більше тягне на h2, оскільки це заголовок секції в рамках всього документу, наступний по рівню після h1

**Comment by VasylUlianovskyi** [comment]
++
