### ISSUE TITLE
відступи

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Blur-Landing-Site#2]
https://github.com/VasylUlianovskyi/Blur-Landing-Site/blob/8679e3929a038dcea6c90526ccc3fbed99e8edfa/README.md?plain=1#L1
- відступи не зовсім заміняються флексами. Зокрема, треба звертати увагу, щоб були відступи зліва і справа блоків, щоб контент не влипав один в один і в краї в'юпорта:
![image](https://github.com/VasylUlianovskyi/Blur-Landing-Site/assets/67504221/99dc876e-7ebe-4262-b8e8-9e432f9e3cad)
Для цього часто зручно використовувати padding. Інколи gap. Хоча в цілому, дійсно, падінгів і марджинів з флексами буде трохи менше)

**Comment by VasylUlianovskyi** [comment]
++
