### ISSUE TITLE
line-height 

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Blur-Landing-Site#4]
https://github.com/VasylUlianovskyi/Blur-Landing-Site/blob/8679e3929a038dcea6c90526ccc3fbed99e8edfa/css/style.css#L75
- висоту рядка надійніше задавати множником (https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#number).

**Comment by VasylUlianovskyi** [comment]
++
