### ISSUE TITLE
центрування

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Blur-Landing-Site#5]
https://github.com/VasylUlianovskyi/Blur-Landing-Site/blob/8679e3929a038dcea6c90526ccc3fbed99e8edfa/css/style.css#L41
- респект, що порозбиралися з блюром і центруванням позиціонованих елементів 👍 Скоро ще розберемо, як центрування можна зробити елегантніше, не підбираючи пікселі.

**Comment by VasylUlianovskyi** [comment]
++
