### ISSUE TITLE
жорсткий падінг

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/Blur-Landing-Site#7]
https://github.com/VasylUlianovskyi/Blur-Landing-Site/blob/8679e3929a038dcea6c90526ccc3fbed99e8edfa/css/style.css#L92
- ту можна замість великого падінгу задати ширину в 50%. Тоді відступ буде зменшуватись при звеженні в'юпорта. Ну і задати ґап, щоб вони не злиплись.

**Comment by VasylUlianovskyi** [comment]
++
